parameters:
    app.slack_token: '%env(SLACK_TOKEN)%'
    app.keycloak.url: '%env(KEYCLOAK_URL)%'
    app.keycloak.realm: '%env(KEYCLOAK_REALM)%'
    app.keycloak.client_id: '%env(KEYCLOAK_CLIENT_ID)%'
    app.keycloak.client_secret: '%env(KEYCLOAK_CLIENT_SECRET)%'
    app.keycloak.user: '%env(KEYCLOAK_USER)%'
    app.keycloak.password: '%env(KEYCLOAK_PASSWORD)%'
    app.google_recaptcha.secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

# --------- Concrete Service Definitions ---------

    App\Service\SlackNotifierService:
        arguments:
            $slackToken: '%app.slack_token%'

    App\Service\GoogleRecaptchaApiService:
        arguments:
            $googleSecret: '%app.google_recaptcha.secret%'

# --------- Interfaces ---------

    App\Service\SlackNotifierServiceInterface: '@App\Service\SlackNotifierService'

    App\Service\GoogleRecaptchaApiServiceInterface: '@App\Service\GoogleRecaptchaApiService'

    App\Service\KeycloakRestApiServiceInterface: '@App\Service\KeycloakRestApiService'
